### ISSUE TITLE
Improved Filters

### ISSUE THREAD

**Issue by bellyflopp** [codeRIT/hackathon-manager#109]
Specific filters based on:

- Status
- School
- etc.

When searching through questionnaires.

**Comment by sman591** [comment]
Implemented in f1008e7 for questionnaires and schools, with a dropdown menu for status

![Column filtering](https://user-images.githubusercontent.com/1441807/58565909-9a7b6d80-81fd-11e9-8d55-ba1c19bd4b69.png)
