### ISSUE TITLE
Notify admins when bus captain leaves bus list

### ISSUE THREAD

**Issue by sman591** [codeRIT/hackathon-manager#114]
If a bus captain leaves the bus list, or RSVP denies, they'll be removed as a bus captain.

Admins (or some email) should be notified of this happening.

Might be best implemented with:
* New mailer
* `after_save` callback on the Questionnaire model that triggers the email if `is_bus_captain` goes from true -> false

**Comment by cbaudouinjr** [comment]
@peterkos I know we're focusing less on bus features because of the current situation of things but I'd like to squeeze this in, this would have solved some major issues for us at the last BrickHack.

**Comment by peterkos** [comment]
Gotcha! Per @sman591's suggestion let's do #174 first to save a bit of refactoring. Doesn't seem like too big of a change so it should fit in nicely.

**Comment by peterkos** [comment]
Blocked on #174
