### ISSUE TITLE
Customizable dashboard chart colors

### ISSUE THREAD

**Issue by sman591** [codeRIT/hackathon-manager#12]
Right now the chart colors are hard-coded in a `chartkick.rb` initializer for BrickHack colors, which can't be customized. Instead they should be customizable per-hackathon.

**Comment by dquach217** [comment]
@sman591 I'm thinking of creating a config file for this, making it customizable. Do you have any inputs on which specific chart is utilizing these hard coded configurations?

**Comment by sman591** [comment]
@dquach217 I looked into this a few weeks ago and noticed there really isn't much to be customized for chart colors, other than a "primary" color (orange for right now). I'm thinking it'd be better to somehow (intelligently) parse the new custom CSS generated by #163 and use the primary color from that, but I'm not sure how performant and/or obvious that'd be... otherwise just adding a single new config variable (`primary_manage_chart_color` or something). Thoughts?

I was also wrong in my first description - most colors are actually taken in the dashboard index.html template, instead of chartkick.rb: https://github.com/codeRIT/hackathon-manager/blob/master/app/views/manage/dashboard/index.html.haml#L1-L6

**Comment by dquach217** [comment]
@sman591 I like the idea to parse the custom CSS generated by #163 , but when you say intelligently I'm quite unsure what you meant. I'm assuming that if they use a shade of purple, the other primary colors would be of a similar shade? Please correct me if I'm wrong. If so, that shouldn't be hard to implement.

**Comment by sman591** [comment]
By "intelligently" I was thinking parse the CSS to make sure we find the `--primary` variable within `:root`, but I guess just doing a basic regex (or similar) search for `--primary: [....];` could work instead, no need to parse the CSS or anything. 

The custom CSS field is technically a free-text field, so someone _could_ edit it an type `--primary: blue;` (or anything else), which I'm not sure Chartkick supports. But I think it's fine to ignore that edge case at least for now.

**Comment by dquach217** [comment]
@sman591 okay that makes a lot more sense then. I can connect with you if I have any blockers in regards to this ticket

**Comment by sman591** [comment]
Cool, sounds good
