### ISSUE TITLE
Cache email events for open & spam stats

### ISSUE THREAD

**Issue by sman591** [codeRIT/hackathon-manager#17]
_From @sman591 on March 29, 2017 17:27_

Sparkpost's API provides a very limited history of events - only up to 10 days or 1000 events, which we easily exceed when sending out bulk emails.

We can easily track these events by opening a webhook that Sparkpost notifies when new events come in.

By doing so, we can display stats like:

* Open rate
* Spam rate
* Unsubscribe rate
* Others?

Providing simple statistics - such as email opens and clicks - can be super helpful when tracking the performance of the emails we send.

_Copied from original issue: codeRIT/brickhack.io#494_

**Comment by dquach217** [comment]
@sman591 Is this issue still relevant since we are moving from Sparkpost to Mailgun?

**Comment by sman591** [comment]
Yeah still relevant, will just be parsing incoming web hooks from Mailgun instead of Sparkpost

**Comment by cbaudouinjr** [comment]
Closed as a result of #286
