### ISSUE TITLE
Migrate from SparkPost to SendGrid

### ISSUE THREAD

**Issue by sman591** [codeRIT/hackathon-manager#174]
SparkPost is killing their free plan and replacing it with a "test" 500 emails/month (100/day max); the cheapest plan up from that is $20/month for 15,000 emails/month, which is already much more than the average hackathon needs.

Thankfully, Mailgun still offers a free 10,000 emails/month. We should switch to them as the de-facto email provider.

In the future we should probably support multiple native providers (SendGrid, AWS, Mandrill, etc) but I think this is fine for now

**Comment by cbaudouinjr** [comment]
@peterkos Pricing for MailGun has changed from 10,000 to 5,000 emails/month. I looked at our invoices for our peak months and we use roughly 75% of this cap for a 600 person hackathon. Did some searching for better pricing and it appears MailGun is still the best option

**Comment by peterkos** [comment]
Just to confirm, 75% of the new 5,000 limit? Should be good if we're targeting ~300 for BH7. 
Also their pricing appears to be 5,000 free every 3 months, so worst case we could be a bit creative with staggering messages out (if possible).

**Comment by peterkos** [comment]
As @cbaudouinjr discovered, MailGun is only 5k emails for the *first* three months, not every three months.
GitHub Education Pack offers a nice [SendGrid](https://sendgrid.com/partner/github-education) deal! 15k emails/month, with API access and a lot of features. Valid as long as the GitHub account its attached to is a student account.
