### ISSUE TITLE
Access user-facing data via non-admin routes on API

### ISSUE THREAD

**Issue by peterkos** [codeRIT/hackathon-manager#222]
Architectural goal of this update is to decouple users and questionnaires. 

Note that first/last names are being moved to the user model too. This way admins do not need to have questionnaires, and can still be considered a full "user". 

Implementation notes for self:
- Email fallback for full name when no questionnaire present is no longer needed
- Moved `first_name` and `last_name` columns from `questionnaire` to `user`
- Moved `full_name` method (?) to `user`

**Comment by dquach217** [comment]
@peterkos do you have er diagram of the changes?

**Comment by sman591** [comment]
Note the user<>questionnaire relationship is already set up (for example, `questionnaire.email` pulls directly from the user) so it doesn't seem like a new relationship has to be defined here. If you do need to create one I'd take a look at https://guides.rubyonrails.org/association_basics.html

**Comment by peterkos** [comment]
@dquach217 Not yet; I'm still planning the changes out. Do you mean any changes in the models/tables?
@sman591 Thanks! That should definitely make things easier. I think this change is mostly around exposing the user data itself to the API and treating that as the default rather than "less than" a questionnaire -- both in other controllers and in the model. So while the relationship might not change, its usage throughout the backend will.

**Comment by peterkos** [comment]
Firstname/lastname refactor took literal months.
Plan is to test that refactor on staging before making API changes that will _finally_ close out this issue
