### ISSUE TITLE
Build hackathon schedule into HM

### ISSUE THREAD

**Issue by JeremyRudman** [codeRIT/hackathon-manager#226]
Potential spike for inprog HM calendar

**Required Features (in progress)**
- [ ] (from #251) Allow public events in schedule to be accessed from a public API

**Comment by JeremyRudman** [comment]
Here is what the calendar pages currently look like
![chrome_2020-06-10_03-02-50](https://user-images.githubusercontent.com/38338616/84237258-0ce88400-aac7-11ea-87a2-9d35310065f2.png)
![chrome_2020-06-10_03-03-04](https://user-images.githubusercontent.com/38338616/84237260-0ce88400-aac7-11ea-9f6a-836f4c6ed0c3.png)
![chrome_2020-06-10_03-03-14](https://user-images.githubusercontent.com/38338616/84237261-0d811a80-aac7-11ea-9796-c3efe5dbe4f2.png)

**Comment by JeremyRudman** [comment]
updated how owners work
![image](https://user-images.githubusercontent.com/38338616/89721040-a7b9ed80-d9a6-11ea-841a-ed38e9ed9a4d.png)

**Comment by peterkos** [comment]
@cbaudouinjr and I realized that building the schedule (in addition to the API) has two parts that need a lot more planning:
- Public schedule (API-accessible)
- Run of Show (internal use for planning the hackathon)

The public schedule seems easy enough to solve on its own, however to deliver a good experience we believe the schedule feature as a whole should be pushed back. That way we won't have to rip out this code if it ends up not meeting our needs down the line, and that'll be a bit messy. 

One option is to **only** make the public-accessibly schedule (+ API support) and ship with 2.1, but we can discuss that at this week's eng meeting.

**Comment by peterkos** [comment]
Run of show has been moved into #379, this issue will only be for hackathon schedule!

**Comment by peterkos** [comment]
@cbaudouinjr Is this in 2.2 or 2.1.2?
