### ISSUE TITLE
Phone number not validated in questionnaire form

### ISSUE THREAD

**Issue by peterkos** [codeRIT/hackathon-manager#234]
Currently any string can be entered and will be considered a valid phone number.

Not sure if this issue applies to emails too; I haven't been able to get UserMailer to work for testing that.

<img width="429" alt="Screen Shot 2020-05-24 at 1 40 30 AM" src="https://user-images.githubusercontent.com/2782749/82746592-8f4f1500-9d5f-11ea-884e-523523ea6506.png">

**Comment by peterkos** [comment]
Would be great if the UI showed an inline form error as the user types; that way they don't have to fill everything out then go back and hunt for the error.

**Comment by JeremyRudman** [comment]
![chrome_2020-06-19_16-49-34](https://user-images.githubusercontent.com/38338616/85179760-be1db580-b24f-11ea-8cd4-ec99e44f2b53.png)
![chrome_2020-06-19_17-04-04](https://user-images.githubusercontent.com/38338616/85179761-be1db580-b24f-11ea-8ef2-bff8ff56e36a.png)
![MySQLWorkbench_2020-06-19_16-51-10](https://user-images.githubusercontent.com/38338616/85179762-be1db580-b24f-11ea-98a0-4a8a788ad4d1.png)
![MySQLWorkbench_2020-06-19_17-04-42](https://user-images.githubusercontent.com/38338616/85179764-be1db580-b24f-11ea-937c-5c30fda90b3d.png)
![chrome_2020-06-19_17-05-27](https://user-images.githubusercontent.com/38338616/85179779-c83fb400-b24f-11ea-9240-365158b74a9b.png)

**Comment by JeremyRudman** [comment]
added a regex to accept phone numbers with these formats and then removed all non numbers except for the plus sign for the country code
(123) 456-7890
(123)456-7890
123-456-7890
123.456.7890
1234567890
+31636363634
075-63546725

**Comment by peterkos** [comment]
Oh nice! 
I'd suggest to change "Invalid Phone Number" to something like "Please enter a valid phone number" -- has a bit more direction imo
