### ISSUE TITLE
Upgrade credential system to work with Rails 5.2

### ISSUE THREAD

**Issue by peterkos** [codeRIT/hackathon-manager#255]
https://medium.com/cedarcode/rails-5-2-credentials-9b3324851336

**Comment by cbaudouinjr** [comment]
Blocked by #291 as additional documentation will be needed for the user during setup.

**Comment by cbaudouinjr** [comment]
Not too sure what the best implementation is for this as we are a unique Rails application. There are a limited number of ways we can implement this that don't add any extra burden on the end user.

- Create a `credentials.rb.enc` file ourselves where `secret_key_base' and `devise_secret_key` simply point to the pre-existing environment variables for `SECRET_KEY_BASE' and `DEVISE_SECRET_KEY` and distribute the master key in our docs. This is probably the easiest as the only environment variable they would have to add is `MASTER_KEY`, however, it is not the standard to distribute the master key.
- Have the user perform a deploy, enter a bash shell on the VM and generate the credentials files from scratch and perform a redeploy. 

We can't ask the users to generate the credential files on their local machine (then push to their VM) as that would require them to install Ruby, Rails, etc.

Regardless we should find a solution for this before we migrate to Rails 6 #309.

**Comment by peterkos** [comment]
> We can't ask the users to generate the credential files on their local machine (then push to their VM) as that would require them to install Ruby, Rails, etc.
