### ISSUE TITLE
Dashboard refreshes every 15s, should be more efficient way 

### ISSUE THREAD

**Issue by peterkos** [codeRIT/hackathon-manager#257]
See `app/assets/javascripts/manage/lib/jquery.chartkickAutoReload.js` for where the reload is happening.

Maybe there's a better way to refresh this data (i.e., _event-driven_).

**Comment by cbaudouinjr** [comment]
Action Cable may be a good option: https://guides.rubyonrails.org/action_cable_overview.html

**Comment by cbaudouinjr** [comment]
Moving to 3.0 as the UI is being overhauled.
