### ISSUE TITLE
Refactor datatables to be more consistent in their implementation

### ISSUE THREAD

**Issue by peterkos** [codeRIT/hackathon-manager#261]
`setupDatatables.js` needs to be removed, and those tables should conform to the structure of other datatables (i.e., `app/datatables/user_datatable.rb`).

**Comment by peterkos** [comment]
I have a deep-seated dislike for datatables and I ask, with a forced smile, if someone else would like to take this issue

**Comment by cbaudouinjr** [comment]
Blocked by #222

**Comment by cbaudouinjr** [comment]
Moving to 3.0 as the UI is being overhauled.
