### ISSUE TITLE
School text-box dropdown in manage/questionnaires/edit missing background

### ISSUE THREAD

**Issue by cbaudouinjr** [codeRIT/hackathon-manager#266]
When editing a questionnaire's school, the auto-complete drop-down is missing a background. This is making it difficult for users to see the available schools to choose from. 

![Screen Shot 2020-06-20 at 7 48 28 PM](https://user-images.githubusercontent.com/22222538/85213657-27282a80-b32f-11ea-9e91-7139a5ed3a69.png)

**Comment by peterkos** [comment]
I noticed this but didnt want to add more issues lol

**Comment by JeremyRudman** [comment]
![chrome_2020-08-08_18-32-48](https://user-images.githubusercontent.com/38338616/89720961-e1d6bf80-d9a5-11ea-84ca-5181469c9f51.png)
