### ISSUE TITLE
Add Sign in with Apple support

### ISSUE THREAD

**Issue by cbaudouinjr** [codeRIT/hackathon-manager#276]
As we make a move to an increased privacy and mobile-centric focus with HackathonManager, Sign in with Apple is a great way for our attendees to quickly create an account on HackathonManager.

**Comment by peterkos** [comment]
> increased privacy and mobile-centric focus

craig, is that you? :o 
<hr>
Yeah we'll need to coordinate this w/ mobile but biggest issues I personally have are:  

- coordinating Apple user account w/ questionnaire  

- handling case where user signs in w/ appleID and already has a defined questionnaire account

For this last issue, from [Apple's docs](https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_rest_api/authenticating_users_with_sign_in_with_apple):
> A user may already have an account in your system, but may attempt to use Sign in with Apple to log in to that account. Sharing the real email address that’s associated with the user’s Apple ID may not help, because it may not be the same email used to create the account with your system. There are a couple of ways you can mitigate this issue:
> - Implement the ASAuthorizationPasswordProvider class to detect and offer keychain credentials that the system already knows about. This works seamlessly to detect and use existing accounts, and prevents new accounts from being created using Sign in with Apple.
> - For new accounts created using Sign in with Apple, let the user know that they have created a new account, and ask if they have any existing accounts to link to.

**Comment by peterkos** [comment]
see `/app/controllers/users/omniauth_callbacks_controller.rb`
