### ISSUE TITLE
Add support for non-MLH hackathons

### ISSUE THREAD

**Issue by cbaudouinjr** [codeRIT/hackathon-manager#288]
As we begin to support non-MLH hackathons we should remove MLH branding where possible to avoid confusion. We'll also have to remove the static MLH Code of Conduct/other policies. With the policy change we should allow organizations to add any number of agreements as they'd like.

**Anticipated Changes**
- [x] Remove MLH Code of Conduct and other related MLH polices and develop dynamic agreements #377 
- [x] Remove MLH Branding from Stats page #459

**Comment by peterkos** [comment]
Needs migration for database cols that rely on agreement
