### ISSUE TITLE
Auth via MLH occasionally fails on first few tries

### ISSUE THREAD

**Issue by sman591** [codeRIT/hackathon-manager#33]
_From @sman591 on January 7, 2017 5:48_

If the time between browser sessions is long enough, the user gets logged out automatically. However, logging in afterwards via MyMLH fails the first try, but clicking sign in the second time works.

_Copied from original issue: codeRIT/brickhack.io#436_

**Comment by sman591** [comment]
I've seen this happen a lot more often over the past month, to the point where I had to just stop and wait a few minutes before trying again.

**Comment by cbaudouinjr** [comment]
Unable to reproduce.
