### ISSUE TITLE
Rebrand “Questionnaires” to be “Applications”

### ISSUE THREAD

**Issue by cbaudouinjr** [codeRIT/hackathon-manager#336]
Currently "Applications" and "Questionnaires" are used interchangeably within manage. To avoid confusion, “ Questionnaires” should be refactored to “Applications”

**Comment by peterkos** [comment]
Noted changes that may need to be refactored by this decision:
- PR #302

**Comment by cbaudouinjr** [comment]
> Noted changes that may need to be refactored by this decision:
> 
> * PR #302

This issue only deals with the management area of HM. That message is sent to all users regardless of role.

**Comment by DJSR59** [comment]
Which directory? I can do it really quick but there's multiple manage folders lol.

**Comment by cbaudouinjr** [comment]
Honestly, after using HM for so long after creating this PR, I forgot this was supposed to be "Applications" -> "Questionnaires" and assumed it was going to be "Questionnaires" -> "Applications". Additionally I think it's easier to understand if users are submitted an "Application" to BrickHack rather than a "Questionnaire"

**Comment by cbaudouinjr** [comment]
Moving to 3.0 as this is a breaking change for any third-party apps reliant on `questionnaire_id` and such.
