### ISSUE TITLE
BrickHack logo missing from login page

### ISSUE THREAD

**Issue by peterkos** [codeRIT/hackathon-manager#350]
<img width="695" alt="image" src="https://user-images.githubusercontent.com/2782749/93006420-fae50a00-f529-11ea-8571-7671467fdbda.png">

**Comment by cbaudouinjr** [comment]
Hey there! This looks like an issue with your local instance of HackathonManager. After inspecting the code, you have your image pointing to an image that doesn't exist on brickhack.io. Maybe we should check for this.

`<img id="logo" alt="BrickHack logo" title="BrickHack" class="header-logo__image" **src="https://brickhack.io/assets/bh-logos/brickhack-6-d8c521dd985c5ea7b6b4d4393be5043e328979ba648f2be7447882881f77f9f1.svg"**>`
