### ISSUE TITLE
Mobile sidebar unable to scroll; "Sign out" too close to hamburger menu

### ISSUE THREAD

**Issue by peterkos** [codeRIT/hackathon-manager#380]
On mobile, after toggling the hamburger menu, the "sidebar" cannot be scrolled.

Also, having a destructive action (sign out) next to the action item (menu button) is... strange. Maybe these buttons can instead go right inside the sidebar? I couldn't find an easy way to do that. 

<img src="https://user-images.githubusercontent.com/2782749/94646593-87c6ec00-02bc-11eb-80cd-336a6c531d82.jpg" width="350px" />

**Comment by peterkos** [comment]
Move hamburger menu to left?

**Comment by sjmiller4rit** [comment]
peter told me to do this :)

**Comment by peterkos** [comment]
^^^ that reopen/close is my fault for not noticing this issue was _mentioned_ in #381 , not _fixed_ in #381 ... long week 😓

**Comment by cbaudouinjr** [comment]
@peterkos Is this good to close?

**Comment by cbaudouinjr** [comment]
^Oops

**Comment by peterkos** [comment]
Yep!
