### ISSUE TITLE
Update user role description + README to conform to new role structure

### ISSUE THREAD

**Issue by peterkos** [codeRIT/hackathon-manager#382]
#345 refactored roles, but the description under the role field on the user edit page does not match the new roles:

![image](https://user-images.githubusercontent.com/2782749/94857481-8e11b100-03ff-11eb-85c9-08693a55be63.png)

Also, README setup instructions for promoting the default account need to be updated to promote user to `:director` instead of `:admin`!

**Comment by chrisgoutzi** [comment]
I would love to try fixing that if you could give me a bit more details

**Comment by peterkos** [comment]
@chrisgoutzi Sure thing!

[Here's](https://coderit.org/hackathon-manager/docs/2.0-whats-new#changes) a list of our role changes from the initial 2.0 release. 

The description in the screenshot when editing a user from the Admin panel (`in manage page>users&staff>click on a user>edit`) refers to `the admin` but we want it to instead be about a `director` -- and same for all other old roles in that description field.

This mistake also exists in the README file, which will need updating to its equivalent new role there too.

Something to note is that we're planning to get all 2.1 issues merged in by the due date on the 2.1 milestone (currently 11/7). If you need any more info, just ask!

**Comment by peterkos** [comment]
@chrisgoutzi Hey, just checking in -- any updates on this issue?
