### ISSUE TITLE
Add "questionnaire_id" to User.as_json

### ISSUE THREAD

**Issue by cbaudouinjr** [codeRIT/hackathon-manager#393]
Currently we do not supply the relation between User and Questionnaire in User.as_json, the ID of the foreign key Questionnaire should be supplied in the User model json so third-party applications can easily identify a questionnaire associated with a user if one exists.

**Comment by peterkos** [comment]
Just to fill in the motivation behind this issue:

This is to add support for Discord bot check-in via [authbot-hm](https://github.com/codeRIT/authbot-hm/).  
Setup process for that is (ideally, for this issue) as follows:
- Discord bot is setup via user who has admin privileges on HM
- GET `user.json`
- `user.json` contains `questionnaireID`
- Bot does GET `/manage/questionnaires?id="questionnaireID"` <-- this is what we are adding 
    - Bot needs to do do this `GET` as we don't want users checking in themselves
