### ISSUE TITLE
add logo to webpage

### ISSUE THREAD

**Issue by Madrugaur** [codeRIT/hackathon-manager#396]
theres no logo for hackathon manager on the browser. Makes it really hard to find it in a lot of tabs.

**Comment by peterkos** [comment]
Do you mean the favicon?

Hmm. Either way HM doesn't have a particular logo yet, although we could just put the codeRIT logo in the tab bar for now. 

Ive been talking with @cbaudouinjr about rebranding HM to something a bit more "brand-y". 

Rebrand might take a while, so how about we just put the codeRIT logo as favicon?

**Comment by peterkos** [comment]
Also rebrand is #397

**Comment by cbaudouinjr** [comment]
Favicon's are configured in `Hackathon Settings` on a per hackathon basis.
