### ISSUE TITLE
Add button to reset databases between hackathons

### ISSUE THREAD

**Issue by peterkos** [codeRIT/hackathon-manager#413]
Between hackathons, events might want to remove all users+questionnaires, but _keep_ messages and other assets.

A button for this somewhere in HM would be helpful, where the director (only) would have to type the name of the event in order to erase, similar to GitHub removing a repo:

<img src="https://user-images.githubusercontent.com/2782749/100683159-c3764480-3345-11eb-8ede-380606afc433.png" width="400px" style="display: inline-block; margin: 0 auto;" />

(Note button is **disabled** until user types repo name)

**Comment by JeremyRudman** [comment]
@peterkos should we exclude directors (such as the person resetting the hackathon) from the removal?

**Comment by peterkos** [comment]
I think so! 
What if we had a checkbox list of things to reset? Like, a director who's wiping it can choose to reset volunteers, organizers, etc. If not, we can just reset all other roles except directors, as they'll likely stay the same.

**Comment by cbaudouinjr** [comment]
@JeremyRudman Just be sure to test audits, that’s  where things are failing the most right now for BrickHack after resetting its DB 5 years in row.

**Comment by JeremyRudman** [comment]
![image](https://user-images.githubusercontent.com/38338616/103364471-e7838d80-4a8b-11eb-80a5-98c9b7ae3800.png)

**Comment by JeremyRudman** [comment]
I choose to use "Reset Hackathon" instead of the hackathon name because I disabled the button through the JavaScript and its incredible janky to send config information (the hackathon name in this case) to the JavaScript.

**Comment by cbaudouinjr** [comment]
> I choose to use "Reset Hackathon" instead of the hackathon name because I disabled the button through the JavaScript and its incredible janky to send config information (the hackathon name in this case) to the JavaScript.

How about for the title it's `Reset HackathonConfig['name']` and the button is just `Reset`?
