### ISSUE TITLE
fix "please read & accept" message location in agreements

### ISSUE THREAD

**Issue by JeremyRudman** [codeRIT/hackathon-manager#464]
The error should pop up under the specific agreement that was not agreed to and not at the bottom of the all the agreements
![image](https://user-images.githubusercontent.com/38338616/102535029-9fb93b00-4075-11eb-8ef6-d065c47df632.png)

**Comment by cbaudouinjr** [comment]
Bug: If a user is missing another required field but has all the agreements selected, it prompts with a "Please read & accept" error
