### ISSUE TITLE
Sidebar title background should fill width of sidebar

### ISSUE THREAD

**Issue by peterkos** [codeRIT/hackathon-manager#481]
![image](https://user-images.githubusercontent.com/2782749/102709449-c8f5e900-4278-11eb-91b3-144b353bc121.png)

**Comment by JeremyRudman** [comment]
fixed spacing in desktop view but with matching bootstrap styling it also changes the mobile view. Personally I think it looks nicer but it could go either way

before
![chrome_2021-01-23_13-28-18](https://user-images.githubusercontent.com/38338616/105610763-4bddf800-5d7f-11eb-83e1-5b46c03bf8bb.png)

after
![image](https://user-images.githubusercontent.com/38338616/105610751-3bc61880-5d7f-11eb-9d6a-38469f3fe518.png)
