### ISSUE TITLE
Add country name to Questionnaire

### ISSUE THREAD

**Issue by cbaudouinjr** [codeRIT/hackathon-manager#547]
Per the updated MLH registration requirements: https://docs.google.com/document/d/1K7HSIEO8tA7vbD0dtwvesMOhDAea8nDKJlu3f3kS8pE/edit

The country data collection will be used to: MLH can send certain promotions to students in select countries. To ensure we send such promotions to the correct hackers, we require this information.

This should be a drop-down to avoid dirty data collection.

**Comment by JeremyRudman** [comment]
tentative 2.2 release
