### ISSUE TITLE
Promote users to admin without requiring them to apply

### ISSUE THREAD

**Issue by sman591** [codeRIT/hackathon-manager#55]
E.g. with a "users" tab instead of just "questionnaires"

Benefits:
* Enable admins to see what accounts exist but don't have applications yet, and mange them
* Can promote accounts to admin status without having an application

**Comment by membrq** [comment]
Can I claim this?

**Comment by sman591** [comment]
@membrq Sure, this is essentially making a new table-based view that loads Users, though it does involve a lot of code. 

Can be accomplished by creating a new `/manage/users` page, essentially a duplicate of the `/manage/admins` page but scoped to all users. This involves:
* Route entry
* New controller
* Tests for new controller
* New datatable model (`app/datatables/`)
* JavaScript support (`setupDatatables.js`)
