### ISSUE TITLE
Convert Rails to API only mode

### ISSUE THREAD

**Issue by cbaudouinjr** [codeRIT/hackathon-manager#666]
Part of the HM 3.0 redesign project.

Reference: https://guides.rubyonrails.org/api_app.html#changing-an-existing-application

**Public Facing:**
- [x] #667
- [x] #668 
- [x] #669 
- [x] #670 
- [x] #672 

**Manage Section:**
- [x] #687 
- [x] #736
- [x] #737
- [x] #738
- [x] #739
- [x] #834 
- [x] #740
- [x] #741
- [x] #742
- [x] #743
- [x] #744
- [x] #745

**Other**
- [x] #747
- [x] #746
- [x] #769
- [x] #825
- [x] #840

**Comment by JeremyRudman** [comment]
I added #835 since it appeared to be missing from the list of stuff we need
