### ISSUE TITLE
Implement style guide in code

### ISSUE THREAD

**Issue by skyegallup** [codeRIT/hackathon-manager#762]
We need to implement the components specified in the [style guide](https://www.figma.com/file/Wrn8Zg87HKtNPNDX5gqMKs/HM-3.0-Style-Guide) so that we can move forward with creating pages.

## Form Components

- [x] Buttons
- [x] Text fields
- [x] Dropdowns
- [x] Checkboxes
- [x] Radio buttons
- [x] Text area

## Layout Components

- [x] Cards
- [x] Vertical groups
- [x] Horizontal groups (navbar)
- [x] Tables

**Comment by peterkos** [comment]
I'm checkin' them off as I do them :)

**Comment by skyegallup** [comment]
Radio buttons and checkboxes have been checked off (get it? checked off? checkboxes? haha)
