### ISSUE TITLE
Re-implement dashboard map

### ISSUE THREAD

**Issue by sman591** [codeRIT/hackathon-manager#83]
The Google Maps APIs are now API-key- and billing-restricted, which makes using them for student-run organizations harder (specifically the billing part; projects are required to have a credit card on file).

All we're using the Google Maps API for is to map cities -> longitude/latitude coordinates, which then get passed to the FCC.gov API for determining FIPS codes (to create a graph of counties). There has to be another API out there that handles this for us.

**Comment by sman591** [comment]
From #58:

Right now, we display a high-level overview of where applicants are applying from, as well as the quantity.

However, if this were an interactive map (e.g. Google Maps overlay), this map could be zoomed in to see:

* Exact location of applicants for planning bus routes
* Visibility into which schools have a bus list active for them

For example: University Abc has a bus, but just down the road is another school with 5 applicants. Right now it's hard for someone to connect the dots, but if this was more precisely visible on a map, someone could see the close distance and be sure to reach out to those students about the bus.

**Comment by dquach217** [comment]
An alternative to using Google API is Open Street Map which is open source and provides us with the same amount of features to what we are using.
